### ISSUE TITLE
Standardization of the dynamic library names so that Mac and Linux could be supported

### ISSUE THREAD

**Issue by jianmingyong** [open-quantum-safe/liboqs-csharp#10]
The current C library wrapper is set to build with liboqs.dll, oqs.so and oqs.dylib respectively.
In order to support Mac and Linux, the file name has to be the same.

Which would be more preferred name to standardize the C# wrapper codes?
"liboqs" or "oqs"

**Comment by dstebila** [comment]
I'm a bit confused here, but also not an expert in this type of thing.  Our liboqs build system, as far as I can tell, builds liboqs.so and liboqs.dylib on Linux/Mac, and oqs.dll.  Are you seeing different names built?

As for a standardized name, should there even be a standardized name?  Windows has different naming conventions than Linux/Mac.  @christianpaquin, any thoughts on Windows?

To enable Mac and Linux support of the .NET wrapper, do we need a standard name, or do we just need to be able to point to one of the correct names depending on the platform?

**Comment by jianmingyong** [comment]
Oops, I may have made a typo on windows file name being liboqs when it was oqs.

Mono has dllmap support which you can choose to resolve dllimport name to different names for other OS all you want but .Net Core does not.

Dllimport in C# is a little annoying to work with when there are different file names for the same set of APIs.

For example, the current C# wrapper is coded to work with oqs.dll. If I build for linux, I would have to use liboqs.so.

The application will not run because the file name does not match. “oqs.dll” and “liboqs.so” is different.

I could kind of solve this on my end by changing the DllImport to “oqs” without the file extension. It would search for the file name only. Then in this case, in order to run the application, I need to change the linux library to “oqs.so”.

Changing file name is the easiest way. The other is to be tedious and implement the same set of api 2 times for two different file name.

There is a NativeLibrary class in .Net Core 3.0 that let you dynamically load dynamic library. Though this also means older apps won’t work if the version is bumped.

**Comment by dstebila** [comment]
If the DLL on the Windows version was called liboqs.dll, and you change DllImport to "liboqs" without the file extension, would that make everything happy?  As for platform conventions, is it okay to have "lib" at the beginning of a DLL's filename?

**Comment by christianpaquin** [comment]
As we discussed on issue #2, @jianmingyong, we are interested in supporting Linux and Mac. It looks like you are on your way of testing that, so any shareable code (that you can submit as a PR) would be interesting to see. Is this naming issue the only problem blocking Linux/Mac, or are there more steps?

Prepending "lib" in front of Windows DLLs is not common, @dstebila; if we choose to do that to simplify this project, then we would need to make sure there are no side effects for the Windows build of our OpenSSL and OpenSSH forks.

**Comment by jianmingyong** [comment]
@christianpaquin Naming the file does make it simple by just removing the dll import file extension. After that it works like a charm.

I understand the concern for other project that might have used the current file naming convention causing unintended side effects. If the OpenSSL and OpenSSH forks used file name to detect the library, it would have been a breaking change.

In that case, it is safe to assume it would be better to have the current file names. I should be able to cook up a PR for that. It results in slightly longer code for the same API but it can ensure compatibility is preserve for both file names.

I will close this first and work on the required change.

**Comment by dstebila** [comment]
@jianmingyong if you are able to do a pull request to make it work, that would be great! Feel free to revisit this issue or make a new one if you need to talk about any of it.
