### ISSUE TITLE
Add circleci test for Linux/macOS build

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/liboqs-csharp#14]

**Comment by baentsch** [comment]
@dstebila Please activate/follow liboqs-dotnet project in CircleCI.

**Comment by dstebila** [comment]
> @dstebila Please activate/follow liboqs-dotnet project in CircleCI.

Done.

**Comment by dstebila** [comment]
Is this resolved by #15?

**Comment by baentsch** [comment]
Functionally, I'd say so. Only question remaining whether @christianpaquin also wants nightly tests (?) to consider this issue fulfilled.

**Comment by christianpaquin** [comment]
> Functionally, I'd say so. Only question remaining whether @christianpaquin also wants nightly tests (?) to consider this issue fulfilled.

I think per-checkin tests are enough.

**Comment by baentsch** [comment]
In that case #15 closes this issue indeed.
