### ISSUE TITLE
Investigate Linux and Mac support

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/liboqs-csharp#2]
Investigate if we can build the .Net core project on Linux and Mac.

**Comment by jianmingyong** [comment]
It is possible to compile using the same code but you need to also compile the oqs library natively for the os and architecture you want to support and copy them into the final product when you want to run them. Though the current code probably resolve to a dll file and will need some modifications to support the “so” and “dylib” for linux and Mac respectively.

**Comment by christianpaquin** [comment]
Yes, indeed, that should make it possible. This issue was opened to keep track of the work item, but isn't a current priority. If this is something that interest you, feel free to submit a PR for it!

**Comment by dstebila** [comment]
Closed by #11.
