### ISSUE TITLE
Build failure on macOS

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs-csharp#20]
liboqs-dotnet builds failing on macOS, see [CircleCI log](https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs-dotnet/164/workflows/6f464424-dce9-4ce2-ae15-a3ad175cfb75/jobs/324).  Appears to be related to an outdated version of netcoreapp.

**Comment by baentsch** [comment]
Can I ask whether it is intentional this failure is invisible both in  https://openquantumsafe.org/dashboard.html and in https://github.com/open-quantum-safe/liboqs-dotnet ? If not (?), I'll add the relevant CI status links to both pages.

**Comment by christianpaquin** [comment]
No, not intentional; go ahead.

**Comment by christianpaquin** [comment]
The .NET core 1.2 used by the CI is [deprecated](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core); will update.
