### ISSUE TITLE
Running Classic-McEliece-8192128f StackOverflow Exception

### ISSUE THREAD

**Issue by jgunter7** [open-quantum-safe/liboqs-csharp#25]
KEM.cs
Exception of type 'System.StackOverflowException' was thrown.
Line 226

When using this:

using (KEM client = new KEM("Classic-McEliece-8192128f"),
                       server = new KEM("Classic-McEliece-8192128f"))

**Comment by jgunter7** [comment]
Seems to occur for all Classic-McEliece variants

**Comment by dstebila** [comment]
The Classic McEliece implementations in liboqs have large stack usage (see notes at https://github.com/open-quantum-safe/liboqs/blob/main/docs/algorithms/kem/classic_mceliece.md) which is probably causing this problem. Are you able to increase the stack allocation at runtime?

**Comment by jgunter7** [comment]
yes, using editbit to set a stack size for the .exe built by VS made this work. Sample command line:
`editbin /stack:50000000 C:\Users\User\Downloads\liboqs-dotnet-master1\liboqs-dotnet-master\dotnetOQSSample\bin\Debug\net5.0\dotnetOQSSample.exe`

This sets the built executable's stack to 50 MB - the Classic McEliece tests then pass.

Thanks
