### ISSUE TITLE
Add support for <oqs/rand.h>

### ISSUE THREAD

**Issue by vsoftco** [open-quantum-safe/liboqs-csharp#9]
We should also provide wrapping support for OQS_randombytes etc. from <oqs/rand.h>. I'm currently implementing this for the C++/Go wrappers.

**Comment by dstebila** [comment]
https://github.com/open-quantum-safe/liboqs-python/issues/18#issuecomment-545622005

**Comment by dstebila** [comment]
Optional feature, closing until someone wants to reopen and do this.
